version: '3'
services:
  mongodb:
    image: 'rakhnin/mongo-arm64'
    ports:
      - 27017:27017
  graphql-server:
    build:
      context: './'
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    environment:
      - mongoURI=mongodb://192.168.1.81:27017/testdb
